export const CUSTOMERS = [
  "GODREJ","HAIER","AMSTRAD","ONIDA","CMI","MARQ","CROMA",
  "BPL","HYUNDAI","SANSUI","VOLTAS","BLUE STAR","SAMSUNG",
  "LG","WHIRLPOOL","DAIKIN", "PANASONIC","CARRIER",
  "ACCERPURE",  "BLACK+DECKER", "TCL","CELLECOR","T-SERIES", 
  "INTEX", "HITACHI", "OTHER", "EXPORT", "KELVIN"
];